# 参考: https://qiita.com/ningenMe/items/e2ed82c9c740ad10d480
name: diff
description: git diffを取得し、指定したディレクトリ以下の変更ファイル数をカウントする

inputs:
  subdir:
    description: チェックするディレクトリ
    required: true
  exclude_pattern:
    description: 除外するパターン(スペース区切り)
    required: false
    default: ''
outputs:
  diff-count:
    value: ${{ steps.diff.outputs.diff-count }}
    description: 変更ファイル数

runs:
  using: composite
  steps:
    - id: diff
      env:
        TARGET_BRANCH: ${{ github.base_ref || 'main' }}
      run: |
        git fetch origin ${TARGET_BRANCH}

        GIT_DIFF_CMD="git diff origin/${TARGET_BRANCH} HEAD --name-only -- ${{ inputs.subdir }}"

        # 除外パターンがあればそれぞれに対して:(exclude)を付ける
        if [ -n "${{ inputs.exclude_pattern }}" ]; then
          for pattern in ${{ inputs.exclude_pattern }}; do
            GIT_DIFF_CMD="$GIT_DIFF_CMD ':(exclude)$pattern'"
          done
        fi

        # コマンドを実行
        files=$(bash -c "$GIT_DIFF_CMD")

        # ファイル数をカウント
        count=$(echo "$files" | grep -v '^$' | wc -l)
        count=$(echo "$count" | tr -d ' ')

        echo "diff-count=$count" >> $GITHUB_OUTPUT
      shell: bash
