name = "trend-diary-cron"
compatibility_date = "2025-04-01"
compatibility_flags = [ "nodejs_compat" ]
main = "./src/cron/worker.ts"

[observability]
enabled = true
head_sampling_rate = 1

[vars]
# 現行値が確定したら上書きすること
QIITA_CRON = "0 */8 * * *"
ZENN_CRON = "0 */8 * * *"

[triggers]
crons = ["0 */8 * * *"]

[[d1_databases]]
binding = "DB"
database_name = "trend-diary-db"
database_id = "${D1_DATABASE_ID}"
migrations_dir = "migrations"
