name = "trend-diary"
compatibility_date = "2025-04-01"
compatibility_flags = [ "nodejs_compat" ]
main = "./src/web/worker.ts"
assets = { directory = "./build/client" }

[observability]
enabled = true
head_sampling_rate = 1

[[d1_databases]]
binding = "DB"
database_name = "trend-diary-db"
database_id = "${D1_DATABASE_ID}"
migrations_dir = "migrations"
