name: Viewに応じたアイテムタイプ設定

on:
 issues:
   types: [opened]

jobs:
 set-item-type:
   runs-on: ubuntu-latest
   steps:
     - name: アイテムタイプを設定
       env:
         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
         PROJECT_NUMBER: "1"
         # 各ボードのView ID
         VIEW_PBI: "1" # PBIボード用View ID
         VIEW_SBI: "3" # SBIボード用View ID 
         FIELD_TYPE: "163048810" # item_typeフィールドのID
       run: |
         # ProjectsのView IDを取得
         VIEW_ID=$(gh api graphql -f query='
           query($org:String!, $project:Int!) {
             organization(login:$org) {
               projectV2(number:$project) {
                 view {
                   id
                 }
               }
             }
           }' -f org=$GITHUB_REPOSITORY_OWNER -f project=$PROJECT_NUMBER --jq '.data.organization.projectV2.view.id')

         # View IDに基づいてitem_typeを設定
         case $VIEW_ID in
           $VIEW_PBI) ITEM_TYPE="PBI" ;;
           $VIEW_SBI) ITEM_TYPE="SBI" ;;
           *) ITEM_TYPE="SBI" ;; # デフォルト値
         esac

         # Projectsのitem_typeフィールドを更新
         gh api graphql -f query='
           mutation($project:ID!, $item:ID!, $value:String!) {
             updateProjectV2ItemFieldValue(input: {
               projectId: $project
               itemId: $item
               fieldId: "$FIELD_TYPE"
               value: $value
             }) {
               projectV2Item { id }
             }
           }' -f value="$ITEM_TYPE"
