name: Runs On Each Supabase Functions
description: 'Supabase Functionsの各ジョブでNode.jsをセットアップするComposite Action'

inputs:
  DENO_COMMAND:
    description: '実行するコマンド'
    required: true
  EXCLUDE_FUNCTIONS:
    description: '除外する関数名のリスト'
    required: false
    default: ()

runs:
  using: 'composite'
  steps:
    - name: RUN
      shell: bash
      run: |
        exclude_functions=${{ inputs.EXCLUDE_FUNCTIONS }}
        for function_name in $(ls supabase/functions); do
          if [[ ! " ${exclude_functions[@]} " =~ " ${function_name} " ]]; then
            ${{ inputs.DENO_COMMAND }} -c supabase/functions/${function_name}/deno.json
          fi
        done
