coverage:
  paths:
    - 'coverage/*.lcov' # プロジェクトルートのcoverageディレクトリ
  acceptable: 80% # 最低限必要なカバレッジ率

# プルリクエストにコメントを投稿
comment:
  if: is_pull_request # PRの時のみコメント
  deletePrevious: true # 前回コメント削除
  hideFooterLink: true # octocovリンクを非表示

# GitHub Actions Job Summaryに追加
summary:
  hideFooterLink: false

codeToTestRatio:
  code:
    - 'supabase/functions/**/*.ts'
  test:
    - 'supabase/functions/**/*.test.ts'
  acceptable: 1:1.2
