coverage:
  paths:
    - 'supabase/functions/**/coverage/*.lcov' # 各関数ディレクトリのcoverage
  acceptable: 80% # 最低限必要なカバレッジ率
  badge:
    path: docs/coverage.svg # バッジを生成する場所

# プルリクエストにコメントを投稿
comment:
  if: is_pull_request # PRの時のみコメント
  deletePrevious: true # 前回コメント削除
  hideFooterLink: true # octocovリンクを非表示

# GitHub Actions Job Summaryに追加
summary:
  hideFooterLink: false
