services:
  postgres:
    image: postgres:latest
    ports:
      - '5432:5432'
    volumes:
      - ./postgresql/.data:/var/lib/postgresql/data/pgdata
      - ./postgresql/postgresql.conf:/etc/postgresql/postgresql.conf
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: trend_diary
      PGDATA: /var/lib/postgresql/data/pgdata
    command: postgres
