name: E2Eテスト環境のセットアップ
description: Node.js、Playwright、PostgreSQLをセットアップしてE2Eテストを実行可能にする

inputs:
  node-version-file:
    description: Node.jsバージョンファイルのパス
    required: true

runs:
  using: composite
  steps:
    - name: Node.jsの構築
      uses: ./.github/actions/setup_node
      with:
        node-version-file: ${{ inputs.node-version-file }}

    - name: Playwrightブラウザのキャッシュ
      uses: actions/cache@v4
      id: playwright-cache
      with:
        path: ~/.cache/ms-playwright
        key: ${{ runner.os }}-playwright-${{ hashFiles('**/package-lock.json') }}

    - name: Playwrightのセットアップ
      if: steps.playwright-cache.outputs.cache-hit != 'true'
      shell: bash
      working-directory: ./application
      run: npx playwright install chromium --with-deps

    - name: DB Migration
      shell: bash
      working-directory: ./application
      env:
        DIRECT_URL: ${{ env.DATABASE_URL }}
      run: npm run db:migrate
