name: Setup Supabase Composite Action
description: 'SupabaseをセットアップするComposite Action'

runs:
  using: 'composite'
  steps:
    - name: Supabase CLIのセットアップ
      uses: supabase/setup-cli@v1

    - name: Supabaseの起動
      shell: bash
      # INFO: DBと認証のみ起動
      run: supabase start --exclude realtime,storage-api,imgproxy,postgrest,postgres-meta,studio,logflare,vector,supavisor,mailpit

    - name: Supabaseのキーを環境変数に設定
      id: get-keys
      shell: bash
      run: |
        SUPABASE_JSON=$(supabase status --output json)
        echo "SUPABASE_ANON_KEY=$(echo $SUPABASE_JSON | jq -r '.ANON_KEY')" >> $GITHUB_ENV
        echo "DATABASE_URL=$(echo $SUPABASE_JSON | jq -r '.DB_URL')" >> $GITHUB_ENV
        echo "DB_URL=$(echo $SUPABASE_JSON | jq -r '.DB_URL')" >> $GITHUB_ENV
        echo "DIRECT_URL=$(echo $SUPABASE_JSON | jq -r '.DB_URL')" >> $GITHUB_ENV
        echo "SUPABASE_URL=$(echo $SUPABASE_JSON | jq -r '.API_URL')" >> $GITHUB_ENV
