name: Setup Supabase Composite Action
description: 'SupabaseをセットアップするComposite Action'

outputs:
  db_url:
    description: 'Supabaseのデータベース接続URL'
    value: ${{ steps.get-keys.outputs.db-url }}
  anon_key:
    description: 'Supabaseのanon key'
    value: ${{ steps.get-keys.outputs.anon-key }}

runs:
  using: 'composite'
  steps:
    - name: Supabase CLIのセットアップ
      uses: supabase/setup-cli@v1

    - name: Supabaseの起動
      shell: bash
      # INFO: DBと認証のみ起動
      run: supabase start --exclude realtime,storage-api,imgproxy,postgrest,postgres-meta,studio,edge-runtime,logflare,vector,supavisor,mailpit

    - name: Supabaseのキー取得
      id: get-keys
      shell: bash
      run: |
        SUPABASE_JSON=$(supabase status --output json)
        echo "db-url=$(echo $SUPABASE_JSON | jq -r '.DB_URL')" >> $GITHUB_OUTPUT
        echo "anon-key=$(echo $SUPABASE_JSON | jq -r '.ANON_KEY')" >> $GITHUB_OUTPUT
