name: 'Test Composite Action'
description: 'テストを実行し、テストカバレッジの可視化まで行うComposite Action'

inputs:
  testCommand:
    description: 'テスト用のコマンド'
    required: true
  coverageName:
    description: 'カバレッジの名前'
    required: false
    default: ''

runs:
  using: 'composite'
  steps:
    - uses: actions/checkout@v4

    - name: Node.jsの構築
      uses: actions/setup-node@v4
      with:
        node-version-file: .node-version

    - name: 依存関係のキャッシュを復元
      uses: actions/cache@v4
      with:
        path: node_modules
        key: ${{ runner.os }}-node-modules-${{ hashFiles('package-lock.json') }}

    - name: テストの実行
      run: ${{ inputs.testCommand }}

    - name: カバレッジの可視化
      if: github.event_name == 'pull_request'
      uses: davelosert/vitest-coverage-report-action@v2
      with:
        name: ${{ inputs.coverageName }}
        comment-on: ${{ github.event_name == 'pull_request' && 'pr' || 'commit' }}
