name: Setup Node.js Composite Action
description: 'Node.jsのバージョンを指定してNode.jsをセットアップするComposite Action'

inputs:
  node-version-file:
    description: 'Node.jsのバージョンが記述されたファイル'
    required: true
    default: '.node-version'
  post-command:
    description: 'Node.jsのセットアップ後に実行するコマンド'
    required: false
    default: ''

runs:
  using: 'composite'
  steps:
    - name: Node.jsの構築
      uses: actions/setup-node@v4
      with:
        node-version-file: ${{ inputs.node-version-file }}

    - name: 依存関係のキャッシュ
      uses: actions/cache@v4
      id: node-modules-cache
      with:
        path: node_modules
        key: ${{ runner.os }}-node-modules-${{ hashFiles('package-lock.json') }}

    - name: ライブラリのインストール
      if: steps.node-modules-cache.outputs.cache-hit != 'true'
      shell: bash
      run: npm ci

    - name: Node.jsのセットアップ後のコマンド実行
      if: ${{ inputs.post-command != '' }}
      shell: bash
      run: |
        echo "Node.jsのセットアップ後のコマンドを実行します"
        eval ${{ inputs.post-command }}
