name: Setup Node.js Composite Action
description: 'Node.jsのバージョンを指定してNode.jsをセットアップするComposite Action'

inputs:
  node-version-file:
    description: 'Node.jsのバージョンが記述されたファイル'
    required: true
    default: '.node-version'

runs:
  using: 'composite'
  steps:
    - name: Node.jsの構築
      uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4
      with:
        node-version-file: ${{ inputs.node-version-file }}

    - name: ライブラリのインストール
      shell: bash
      working-directory: ${{ github.workspace }}/application
      run: npm ci

    - name: Prismaクライアントの生成
      shell: bash
      working-directory: ${{ github.workspace }}/application
      run: npm run setup
