name: Setup Node.js Composite Action
description: 'Node.jsのバージョンを指定してNode.jsをセットアップし、オプションのポストコマンドを実行するComposite Action'

inputs:
  node-version-file:
    description: 'Node.jsのバージョンが記述されたファイル'
    required: true
    default: '.node-version'
  post-command:
    description: 'セットアップ後に実行する追加コマンド'
    required: false
    default: ''

runs:
  using: 'composite'
  steps:
    - name: Node.jsの構築
      uses: actions/setup-node@v4
      with:
        node-version-file: ${{ inputs.node-version-file }}

    - name: 依存関係のキャッシュ
      uses: actions/cache@v4
      id: node-modules-cache
      with:
        path: node_modules
        key: ${{ runner.os }}-node-modules-${{ hashFiles('package-lock.json') }}

    - name: ライブラリのインストール
      if: steps.node-modules-cache.outputs.cache-hit != 'true'
      shell: bash
      run: npm ci

    - name: 構築後の追加コマンド実行
      if: inputs.post-command != ''
      shell: bash
      run: ${{ inputs.post-command }}
