name: Setup Node.js Composite Action
description: 'Node.jsのバージョンを指定してNode.jsをセットアップするComposite Action'

inputs:
  nodeVersionFile:
    description: 'Node.jsのバージョンが記述されたファイル'
    required: true
    default: '.node-version'

runs:
  using: 'composite'
  steps:
    - name: Node.jsの構築
      uses: actions/setup-node@v4
      with:
        node-version-file: ${{ env.NODE_VERSION_FILE }}

    - name: 依存関係のキャッシュ
      uses: actions/cache@v4
      id: node-modules-cache
      with:
        path: node_modules
        key: ${{ runner.os }}-node-modules-${{ hashFiles('package-lock.json') }}

    - name: ライブラリのインストール
      if: steps.node-modules-cache.outputs.cache-hit != 'true'
      shell: bash
      run: npm ci
