name: Setup Prisma Composite Action
description: 'Prismaクライアントのキャッシュと生成を行うComposite Action'

inputs:
  schema-path:
    description: 'Prismaスキーマファイルのパス'
    required: false
    default: 'prisma/main.prisma'

runs:
  using: 'composite'
  steps:
    - name: Prisma関連ファイルのキャッシュ
      uses: actions/cache@v4
      id: prisma-cache
      with:
        path: |
          node_modules/.prisma
          node_modules/@prisma/client
        key: ${{ runner.os }}-prisma-${{ hashFiles(inputs.schema-path) }}

    - name: Prismaクライアント生成
      shell: bash
      run: |
        echo "Prismaクライアントを生成します"
        # すでにPrismaがインストールされている前提
        npx prisma generate
        echo "Prismaクライアント生成完了"

    - name: キャッシュステータスの出力
      shell: bash
      run: |
        if [ "${{ steps.prisma-cache.outputs.cache-hit }}" = "true" ]; then
          echo "Prismaキャッシュがヒットしました。ただし最新のスキーマで再生成しています。"
        else
          echo "Prismaキャッシュはヒットしませんでした。新しいキャッシュを作成しています。"
        fi
