name: 'Test Composite Action'
description: 'テストを実行し、テストカバレッジの可視化まで行うComposite Action'

inputs:
  test-command:
    description: 'テスト用のコマンド'
    required: true
  coverage-name:
    description: 'カバレッジの名前'
    required: false
    default: ''

runs:
  using: 'composite'
  steps:
    - name: テストの実行
      shell: bash
      run: ${{ inputs.test-command }}

    - name: カバレッジの可視化
      if: github.event_name == 'pull_request'
      uses: davelosert/vitest-coverage-report-action@v2
      with:
        name: ${{ inputs.coverage-name }}
        comment-on: ${{ github.event_name == 'pull_request' && 'pr' || 'commit' }}
