name: 'Test Composite Action'
description: 'テストを実行し、テストカバレッジの可視化まで行うComposite Action'

inputs:
  target:
    description: 'テスト対象 (frontend, api, domain)'
    required: true

runs:
  using: 'composite'
  steps:
    - name: テストの実行
      shell: bash
      run: npm run test:${{ inputs.target }} -- --coverage

    - name: カバレッジの可視化
      if: github.event_name == 'pull_request'
      uses: davelosert/vitest-coverage-report-action@v2
      with:
        name: ${{ inputs.target }}
        vite-config-path: vitest/config.${{ inputs.target }}.ts
        comment-on: ${{ github.event_name == 'pull_request' && 'pr' || 'commit' }}
