name: Auto Format

on:
  push:
    branches-ignore:
      - main

permissions:
  contents: read

env:
  BIOME_VERSION: 2.0.6

defaults:
  run:
    shell: bash
    working-directory: ./application

jobs:
  auto-format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4

      - name: Setup Biome
        uses: biomejs/setup-biome@a05c02a1304287da45f13648675a70d5841acdbc # v2
        with:
          version: ${{ env.BIOME_VERSION }}

      - name: Check format
        run: biome format --diagnostic-level=error .
