name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

# カバレッジの可視化で、コメントを残すための権限
permissions:
  contents: read
  pull-requests: write

# 連続push時に同じジョブが並列で実行されるのを防ぐ
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  NODE_VERSION_FILE: .node-version

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Node.jsの構築
        uses: actions/setup-node@v4
        with:
          node-version-file: ${{ env.NODE_VERSION_FILE }}

      - name: 依存関係のキャッシュ
        uses: actions/cache@v4
        id: node-modules-cache
        with:
          path: node_modules
          key: ${{ runner.os }}-node-modules-${{ hashFiles('package-lock.json') }}

      - name: ライブラリのインストール
        if: steps.node-modules-cache.outputs.cache-hit != 'true'
        run: npm ci

  lint:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Node.jsの構築
        uses: actions/setup-node@v4
        with:
          node-version-file: ${{ env.NODE_VERSION_FILE }}

      - name: 依存関係のキャッシュを復元
        uses: actions/cache@v4
        with:
          path: node_modules
          key: ${{ runner.os }}-node-modules-${{ hashFiles('package-lock.json') }}

      - name: Lint
        run: npm run lint

  format:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Node.jsの構築
        uses: actions/setup-node@v4
        with:
          node-version-file: ${{ env.NODE_VERSION_FILE }}

      - name: 依存関係のキャッシュを復元
        uses: actions/cache@v4
        with:
          path: node_modules
          key: ${{ runner.os }}-node-modules-${{ hashFiles('package-lock.json') }}

      - name: Format
        run: npm run format

  # 本来であれば、概念的にコンパイルはLint/Formatと同列ではないが、実行時間短縮のために並列実行にしている
  ts-compile-check:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Node.jsの構築
        uses: actions/setup-node@v4
        with:
          node-version-file: ${{ env.NODE_VERSION_FILE }}
      - name: 依存関係のキャッシュを復元
        uses: actions/cache@v4
        with:
          path: node_modules
          key: ${{ runner.os }}-node-modules-${{ hashFiles('package-lock.json') }}
      - name: TypeScript型チェック
        run: npm run check-types

  test-frontend:
    needs: [lint, format, ts-compile-check]
    runs-on: ubuntu-latest
    steps:
      - name: フロントエンドのテスト
        uses: ./.github/actions/test_cov
        with:
          coverageName: 'Frontend'
          testCommand: 'npm run test:frontend:coverage'

  test-backend:
    needs: [lint, format, ts-compile-check]
    runs-on: ubuntu-latest
    steps:
      - name: バックエンドのテスト
        uses: ./.github/actions/test_cov
        with:
          coverageName: 'Backend'
          testCommand: 'npm run test:backend:coverage'
