name: スプリントとタイプ設定
on:
 issues:
   types: [opened]

jobs:
 set-fields:
   runs-on: ubuntu-latest
   env:
     ORG: Geek-Teck-Mentors
     PROJECT_NUMBER: 1
     FIELD_SPRINT: Sprint
     ITERATION: current
   steps:
     - name: スプリントとタイプ設定
       run: |
         PROJECT_ID=$(gh api graphql -f query='
           query($org: String!) {
             organization(login: $org) {
               projectV2(number: ${{ env.PROJECT_NUMBER }}) {
                 id
               }
             }
           }
         ' -f org="${{ env.ORG }}" --jq '.data.organization.projectV2.id')
         
         ITEM_ID=$(gh api graphql -f query='
           mutation($projectId: ID!, $issueId: ID!) {
             addProjectV2ItemById(input: {projectId: $projectId, contentId: $issueId}) {
               item {
                 id
               }
             }
           }
         ' -f projectId="$PROJECT_ID" -f issueId="${{ github.event.issue.node_id }}" --jq '.data.addProjectV2ItemById.item.id')
         
         gh api graphql -f query='
           mutation($itemId: ID!, $fieldId: ID!, $iterationId: ID!) {
             updateProjectV2ItemFieldValue(
               input: {
                 itemId: $itemId
                 fieldId: $fieldId
                 value: {
                   iterationId: $iterationId
                 }
               }
             ) {
               projectV2Item {
                 id
               }
             }
           }
         ' -f itemId="$ITEM_ID" -f fieldId="${{ env.FIELD_SPRINT }}" -f iterationId="${{ env.ITERATION }}"
