name: スプリントとタイプを設定する
on:
 issues:
   types: [opened]
jobs:
 set-fields:
   runs-on: ubuntu-latest
   env:
     # GitHub Project設定
     PROJECT_NUMBER: 1
     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
     # フィールドID
     FIELD_TYPE_ID: 163048810
     FIELD_SPRINT: Sprint
     # 値設定
     TYPE_VALUE: SBI
   steps:
     - name: カレントスプリントに追加
       uses: blombard/move-to-next-iteration@master
       with:
         owner: ${{ github.repository_owner }}
         number: ${{ env.PROJECT_NUMBER }}
         token: ${{ env.GITHUB_TOKEN }}
         iteration-field: ${{ env.FIELD_SPRINT }}
         iteration: new
         new-iteration: current

     - name: タイプを設定
       run: |
         gh api graphql -f query='
           mutation($value: String!) {
             updateProjectV2ItemFieldValue(input: {
               fieldId: "$FIELD_TYPE_ID"
               value: {
                 singleSelectOptionId: $value
               }
             }) {
               clientMutationId
             }
           }
         ' -f value="${{ env.TYPE_VALUE }}"
