name: SBIタイプとフィールド設定

on:
 issues:
   types: [opened]

jobs:
 set-sbi-type:
   if: ${{ env.VIEW_ID == env.VIEW_SBI }}
   runs-on: ubuntu-latest
   steps:
     - name: SBIタイプとフィールドを設定
       env:
         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
         PROJECT_NUMBER: "1"
         # Projects設定
         VIEW_SBI: "3"
         FIELD_TYPE_ID: "163048810"
         FIELD_SPRINT_ID: "163048199" 
         FIELD_PROGRESS_ID: "163048200" # Progressフィールド
         # 定数
         ITEM_TYPE_VALUE: "SBI"
         SPRINT_VALUE: "Current"
         PROGRESS_VALUE: "Status" # デフォルト値
       run: |
         # item_type設定
         gh api graphql -f query='
           mutation($project:ID!, $item:ID!) {
             updateProjectV2ItemFieldValue(input: {
               projectId: $project
               itemId: $item
               fieldId: "$FIELD_TYPE_ID"
               value: "$ITEM_TYPE_VALUE"
             }) {
               projectV2Item { id }
             }
           }'
           
         # スプリント設定
         gh api graphql -f query='
           mutation($project:ID!, $item:ID!) {
             updateProjectV2ItemFieldValue(input: {
               projectId: $project
               itemId: $item
               fieldId: "$FIELD_SPRINT_ID"
               value: "$SPRINT_VALUE"
             }) {
               projectV2Item { id }
             }
           }'

         # Progress設定
         gh api graphql -f query='
           mutation($project:ID!, $item:ID!) {
             updateProjectV2ItemFieldValue(input: {
               projectId: $project
               itemId: $item
               fieldId: "$FIELD_PROGRESS_ID"
               value: "$PROGRESS_VALUE"
             }) {
               projectV2Item { id }
             }
           }'
