name: Supabase CI
description: SupabaseプロジェクトのCI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
    paths:
      - 'supabase/**'
      - '.github/workflows/functions_ci.yaml'

env:
  DENO_VERSION: 2.3.1
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Denoの構築
        uses: denoland/setup-deno@v2
        with:
          deno-version: ${{ env.DENO_VERSION }}
      - name: Lint
        run: deno lint -c supabase/style_config.json

  format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Denoの構築
        uses: denoland/setup-deno@v2
        with:
          deno-version: ${{ env.DENO_VERSION }}
      - name: Format
        run: deno fmt --check -c supabase/style_config.json
