name: UI Test

on: 
  push:
    paths:
      - 'src/application/web/**/*.tsx'
      - 'vitest/config.storybook.ts'
      - '.github/workflows/test-ui.yaml'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Node.jsの構築
        uses: ./.github/actions/setup_node

      - name: Run tests
        run: npm run test-storybook -- --coverage
