name: UI Test

on: 
  push:
    branches:
      - main
    paths:
      - 'src/application/web/**/*.tsx'
      - 'vitest/config.storybook.ts'
      - '.github/workflows/test-ui.yaml'
  pull_request:
    branches:
      - main
    paths:
      - 'src/application/web/**/*.tsx'
      - 'vitest/config.storybook.ts'
      - '.github/workflows/test-ui.yaml'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Node.jsの構築
        uses: ./.github/actions/setup_node

      - name: Playwrightブラウザのキャッシュ
        uses: actions/cache@v4
        id: playwright-cache
        with:
          path: ~/.cache/ms-playwright
          key: ${{ runner.os }}-playwright-${{ hashFiles('**/package-lock.json') }}
      - name: Playwrightのセットアップ
        if: steps.playwright-cache.outputs.cache-hit != 'true'
        run: npx playwright install chromium --with-deps

      - name: Run tests
        run: npm run test-storybook
